import AreaChart from "@/components/charts/AreaChart";
import { generateMonthLabel } from "@/utils/months";
import { generateLineData } from "@/utils/generateData";
import { generateColor } from "@/utils/generateColor";

export const metadata = {
	title: "Simulator",
	description: "Generated by create next app",
};

export default function Page() {
	const data = generateLineData(12, 300, 2000);
	return (
		<div className="my-10 sm:mx-4 xl:mx-10">
			<div className="flex items-center w-full mb-10">
				<h2 className="text-2xl md:text-3xl font-bold tracking-tight max-w-6xl">
					Stock Simulator
				</h2>
			</div>

			<div className="flex flex-col justify-center items-center gap-6">
				{Array.from({ length: 4 }).map((_, index) => {
					const color = generateColor();
					const data = generateLineData(12, 1000, 3000);
					return (
						<AreaChart
							key={index}
							labels={generateMonthLabel(data)}
							datasets={[
								{
									fill: true,
									label: `Stock ${index + 1}`,
									data: data,
									borderColor: `rgb(${color})`,
									backgroundColor: `rgb(${color}, .4)`,
								},
							]}
							monthTracker={data.length}
							year={2023}
						/>
					);
				})}
			</div>
		</div>
	);
}
